version: '3.8'
services:
  app:
    image: jekyll/jekyll:pages
    container_name: pages
    tty: true
    command: jekyll serve --force_polling
    volumes:
      - $PWD:/srv/jekyll
    ports:
      - 4000:4000